table _Medidas
	lineageTag: 7a641823-7cda-46dc-ab66-b6ea2ffc0744

	measure 'Lucro Bruto' = SUM(fVendas[LUCRO_TOTAL])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1b2b9e1c-5089-4e9f-b119-83e445472653

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Margem %' = DIVIDE([Lucro Bruto], [Total Receita], 0)
		lineageTag: e4aeb396-44b2-443b-b138-b0b72cd3b86c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rank Vendedor' =
			
			RANKX(
			    ALL(dVendedor[NOME]),
			    [Total Receita],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: a9f790b2-6c03-4da0-bfef-ae192a918a83

	measure 'Receita Eletronicos' =
			
			CALCULATE(
			    [Total Receita],
			    dCategoria[NOME] IN {"CELULARES","INFORMATICA","TV E AUDIO"}
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 5946beba-49ed-4000-a947-d6d39061c901

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Custo' = SUM(fVendas[CUSTO_TOTAL])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 100f2cb6-21b1-41b8-9f64-2592760509f7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Receita' = SUM(fVendas[TOTAL_ITEM])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: facc93dd-f2fb-4930-997f-94697f87d656

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'HTML Abertura' = "<div style=""position:absolute;inset:0;width:100%;height:100%;min-height:680px;background:#09091A;background-image:radial-gradient(ellipse 70% 50% at 50% 0%, rgba(139,92,246,0.10) 0%, transparent 70%);display:flex;align-items:center;justify-content:center;font-family:'Segoe UI',sans-serif""><style>@keyframes iavpulse{0%,100%{opacity:.35;transform:scaleX(.82)}50%{opacity:1;transform:scaleX(1)}}@keyframes iavslide{0%{left:-40%}100%{left:100%}}.iavbar{height:6px;border-radius:9999px;background:#8B5CF6;transform-origin:left center;animation:iavpulse 1.4s ease-in-out infinite}.iavtrack{position:relative;width:240px;height:3px;border-radius:9999px;background:rgba(255,255,255,0.08);overflow:hidden;margin:0 auto}.iavtrack:after{content:'';position:absolute;top:0;left:0;height:100%;width:40%;border-radius:9999px;background:linear-gradient(90deg,#7C3AED,#8B5CF6,#A78BFA);animation:iavslide 1.5s cubic-bezier(.65,0,.35,1) infinite}</style><div style=""text-align:center""><div style=""display:flex;align-items:center;gap:18px;justify-content:center;margin-bottom:30px""><div style=""display:flex;flex-direction:column;gap:7px;align-items:flex-start""><span class=""iavbar"" style=""width:58px""></span><span class=""iavbar"" style=""width:38px;animation-delay:.18s""></span><span class=""iavbar"" style=""width:20px;animation-delay:.36s""></span></div><div style=""text-align:left""><div style=""font-size:40px;font-weight:700;letter-spacing:-0.03em;line-height:1;color:#fff"">IA Vendas</div><div style=""font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#70709A;margin-top:8px"">Grupo 4 &middot; Biopark Edu</div></div></div><div class=""iavtrack""></div><div style=""font-size:13px;letter-spacing:0.04em;color:#B0B0CC;margin-top:22px"">Carregando an&aacute;lise de vendas&hellip;</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000002

	measure 'Clientes Únicos' = DISTINCTCOUNT(dCliente[IDCLIENTE])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000010

	measure 'Total Quantidade' = SUM(fVendas[QUANTIDADE])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000011

	measure 'Qtd Fornecedores' = DISTINCTCOUNT(dFornecedor[IDFORNECEDOR])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000012

	measure 'Qtd Estados' = DISTINCTCOUNT(dCliente[ESTADO])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000013

	measure 'Fornecedores Vendendo' = DISTINCTCOUNT(fVendas[IDFORNECEDOR])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000014

	measure 'HTML Logo' = "<div style=""display:flex;align-items:center;gap:11px;height:100%;padding-left:6px;font-family:'Segoe UI',sans-serif""><div style=""display:flex;flex-direction:column;gap:4px""><span style=""display:block;height:4px;width:30px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:19px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:9px;border-radius:9px;background:#8B5CF6""></span></div><div><div style=""font-size:18px;font-weight:700;color:#fff;line-height:1"">IA Vendas</div><div style=""font-size:8px;letter-spacing:0.14em;text-transform:uppercase;color:#70709A;margin-top:3px"">Grupo 4</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000015

	measure 'Nº de Pedidos' = DISTINCTCOUNT(fVendas[IDNOTA])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000020

	measure 'Ticket Médio' = DIVIDE([Total Receita], [Nº de Pedidos])
		formatString: "R$"\ #,0.00
		lineageTag: a1a1a1a1-0000-4000-8000-000000000021

	measure 'HTML Sidebar' = "<div style=""height:100%;box-sizing:border-box;background:#0B0B1A;border-right:1px solid #1C1C30;padding-top:16px;font-family:'Segoe UI',sans-serif""><div style=""display:flex;align-items:center;gap:10px;height:80px;padding-left:18px""><div style=""display:flex;flex-direction:column;gap:4px""><span style=""display:block;height:4px;width:28px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:18px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:9px;border-radius:9px;background:#8B5CF6""></span></div><div><div style=""font-size:17px;font-weight:700;color:#fff;line-height:1"">IA Vendas</div><div style=""font-size:8px;letter-spacing:0.14em;text-transform:uppercase;color:#70709A;margin-top:3px"">Grupo 4</div></div></div><div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Visão Geral</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Clientes</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Produtos</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Fornecedores</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Regiões</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Vendas</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000030

	measure 'Receita Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Total Receita]
			VAR _ant = CALCULATE([Total Receita], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000040

	measure 'Lucro Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Lucro Bruto]
			VAR _ant = CALCULATE([Lucro Bruto], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000041

	measure 'Pedidos Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Nº de Pedidos]
			VAR _ant = CALCULATE([Nº de Pedidos], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000042

	measure 'Ticket Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Ticket Médio]
			VAR _ant = CALCULATE([Ticket Médio], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000043

	measure 'HTML Card Receita' =
			VAR _v = "R$ " & FORMAT([Total Receita], "#,0")
			VAR _var = [Receita Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Receita Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='12' y1='2' x2='12' y2='22'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000050

	measure 'HTML Card Lucro' =
			VAR _v = "R$ " & FORMAT([Lucro Bruto], "#,0")
			VAR _var = [Lucro Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Lucro Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='22 7 13.5 15.5 8.5 10.5 2 17'/><polyline points='16 7 22 7 22 13'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000051

	measure 'HTML Card Ticket' =
			VAR _v = "R$ " & FORMAT([Ticket Médio], "#,0.00")
			VAR _var = [Ticket Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Ticket Médio</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z'/><path d='M16 8h-6'/><path d='M16 12h-6'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000052

	measure 'HTML Card Pedidos' =
			VAR _v = FORMAT([Nº de Pedidos], "#,0")
			VAR _var = [Pedidos Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Nº de Pedidos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='8' cy='21' r='1'/><circle cx='19' cy='21' r='1'/><path d='M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000053

	measure 'HTML Top Clientes' =
			VAR _base =
				ADDCOLUMNS(
					TOPN(6, SUMMARIZE(dCliente, dCliente[NOME], dCliente[REGIAO]), [Total Receita], DESC),
					"@rec", [Total Receita],
					"@ped", [Nº de Pedidos]
				)
			VAR _rk = ADDCOLUMNS(_base, "@rk", RANKX(_base, [@rec], , DESC, DENSE))
			VAR _rows =
				CONCATENATEX(
					_rk,
					"<tr style='border-top:1px solid #16162A'><td style='padding:9px 8px;white-space:nowrap'><span style='display:inline-block;width:20px;height:20px;line-height:20px;text-align:center;border-radius:6px;background:rgba(139,92,246,0.15);color:#A78BFA;font-size:11px;font-weight:700;margin-right:9px'>"
					& [@rk] & "</span><span style='color:#E5E7EB;font-size:12.5px'>" & dCliente[NOME]
					& "</span></td><td style='padding:9px 8px;color:#7A7A98;font-size:12px'>" & dCliente[REGIAO]
					& "</td><td style='padding:9px 8px;text-align:right;color:#C8C8DC;font-size:12px'>" & FORMAT([@ped], "#,0")
					& "</td><td style='padding:9px 8px;text-align:right;color:#fff;font-size:12.5px;font-weight:600'>R$ " & FORMAT([@rec], "#,0")
					& "</td><td style='padding:9px 8px;text-align:right'><span style='display:inline-flex;align-items:center;gap:5px;background:rgba(52,211,153,0.12);color:#34D399;font-size:11px;padding:2px 8px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#34D399;display:inline-block'></span>Ativo</span></td></tr>",
					"",
					[@rec], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px'><div style='display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px'><div><div style='font-size:15px;font-weight:600;color:#fff'>Top Clientes</div><div style='font-size:11px;color:#8888A8;margin-top:2px'>Maiores receitas</div></div></div><table style='width:100%;border-collapse:collapse'><thead><tr><th style='text-align:left;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Cliente</th><th style='text-align:left;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Região</th><th style='text-align:right;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Pedidos</th><th style='text-align:right;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Receita</th><th style='text-align:right;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Status</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000060

	measure 'Total Clientes' = COUNTROWS(dCliente)
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000070

	measure 'Clientes Ativos' = CALCULATE(COUNTROWS(dCliente), FILTER(dCliente, ISBLANK(dCliente[FIM])))
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000071

	measure 'HTML Card Total Clientes' =
			VAR _v = FORMAT([Total Clientes], "#,0")
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Total Clientes</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M22 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>base completa</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000072

	measure 'HTML Card Clientes Ativos' =
			VAR _v = FORMAT([Clientes Ativos], "#,0")
			VAR _pct = FORMAT(DIVIDE([Clientes Ativos], [Total Clientes]), "0%")
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Clientes Ativos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='8.5' cy='7' r='4'/><polyline points='17 11 19 13 23 9'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:#34D399;margin-top:8px'>" & _pct & " ativos</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000073

	measure 'HTML Card Clientes Unicos' =
			VAR _v = FORMAT([Clientes Únicos], "#,0")
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Clientes Únicos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='4' y1='9' x2='20' y2='9'/><line x1='4' y1='15' x2='20' y2='15'/><line x1='10' y1='3' x2='8' y2='21'/><line x1='16' y1='3' x2='14' y2='21'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>clientes únicos</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000074

	measure 'HTML Card Ticket Cliente' =
			VAR _v = "R$ " & FORMAT([Ticket Médio], "#,0.00")
			VAR _var = [Ticket Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), "ticket médio geral", (IF(_up, "+", "") & FORMAT(_var, "0.0%") & " vs mês ant."))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Ticket Médio</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z'/><path d='M16 8h-6'/><path d='M16 12h-6'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & "</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000075

	measure 'HTML Top Clientes Detalhado' =
			VAR _base =
				ADDCOLUMNS(
					TOPN(8, SUMMARIZE(dCliente, dCliente[NOME], dCliente[CIDADE], dCliente[ESTADO], dCliente[REGIAO]), [Total Receita], DESC),
					"@rec", [Total Receita], "@ped", [Nº de Pedidos], "@tk", [Ticket Médio]
				)
			VAR _rk = ADDCOLUMNS(_base, "@rk", RANKX(_base, [@rec], , DESC, DENSE))
			VAR _th = "<th style='text-align:left;padding:7px 10px;color:#6B6B85;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>"
			VAR _thn = "<th style='text-align:right;padding:7px 10px;color:#6B6B85;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>"
			VAR _rows =
				CONCATENATEX(
					_rk,
					"<tr style='border-top:1px solid #16162A'><td style='padding:8px 10px;white-space:nowrap'><span style='display:inline-block;width:20px;height:20px;line-height:20px;text-align:center;border-radius:6px;background:rgba(139,92,246,0.15);color:#A78BFA;font-size:10.5px;font-weight:700;margin-right:8px'>"
					& [@rk] & "</span><span style='color:#E5E7EB;font-size:12px'>" & dCliente[NOME]
					& "</span></td><td style='padding:8px 10px;color:#9A9AB5;font-size:11.5px'>" & dCliente[CIDADE]
					& "</td><td style='padding:8px 10px;color:#9A9AB5;font-size:11.5px'>" & dCliente[ESTADO]
					& "</td><td style='padding:8px 10px;color:#7A7A98;font-size:11.5px'>" & dCliente[REGIAO]
					& "</td><td style='padding:8px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@ped], "#,0")
					& "</td><td style='padding:8px 10px;text-align:right;color:#fff;font-size:12px;font-weight:600'>R$ " & FORMAT([@rec], "#,0")
					& "</td><td style='padding:8px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>R$ " & FORMAT([@tk], "#,0")
					& "</td><td style='padding:8px 10px;text-align:right'><span style='display:inline-flex;align-items:center;gap:5px;background:rgba(52,211,153,0.12);color:#34D399;font-size:10.5px;padding:2px 8px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#34D399;display:inline-block'></span>Ativo</span></td></tr>",
					"",
					[@rec], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px'><div style='font-size:15px;font-weight:600;color:#fff'>Top Clientes</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>Maiores receitas · detalhado</div><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Cliente</th>" & _th & "Cidade</th>" & _th & "Estado</th>" & _th & "Região</th>"
				& _thn & "Pedidos</th>" & _thn & "Receita</th>" & _thn & "Ticket</th>" & _thn & "Status</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000076

	measure 'HTML Todos Clientes' =
			VAR _ord = SELECTEDVALUE('Ordenar Clientes'[Opção], "Receita (maior)")
			VAR _base =
				ADDCOLUMNS(
					SUMMARIZE(dCliente, dCliente[NOME], dCliente[CIDADE], dCliente[ESTADO], dCliente[REGIAO]),
					"@rec", [Total Receita], "@ped", [Nº de Pedidos], "@tk", [Ticket Médio]
				)
			VAR _sorted =
				ADDCOLUMNS(_base, "@sk",
					SWITCH(_ord,
						"Nome (A-Z)", RANKX(_base, dCliente[NOME], , ASC, DENSE),
						"Pedidos (maior)", RANKX(_base, [@ped], , DESC, DENSE),
						"Ticket (maior)", RANKX(_base, [@tk], , DESC, DENSE),
						RANKX(_base, [@rec], , DESC, DENSE)
					))
			VAR _th = "<th style='position:sticky;top:0;background:#14142A;text-align:left;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _thn = "<th style='position:sticky;top:0;background:#14142A;text-align:right;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _rows =
				CONCATENATEX(
					_sorted,
					"<tr style='border-top:1px solid #16162A'><td style='padding:7px 10px;white-space:nowrap'><span style='display:inline-block;min-width:22px;height:20px;line-height:20px;text-align:center;border-radius:6px;background:rgba(139,92,246,0.15);color:#A78BFA;font-size:10.5px;font-weight:700;margin-right:8px;padding:0 4px'>"
					& [@sk] & "</span><span style='color:#E5E7EB;font-size:12px'>" & dCliente[NOME]
					& "</span></td><td style='padding:7px 10px;color:#9A9AB5;font-size:11.5px'>" & dCliente[CIDADE]
					& "</td><td style='padding:7px 10px;color:#9A9AB5;font-size:11.5px'>" & dCliente[ESTADO]
					& "</td><td style='padding:7px 10px;color:#7A7A98;font-size:11.5px'>" & dCliente[REGIAO]
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@ped], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right;color:#fff;font-size:12px;font-weight:600'>R$ " & FORMAT([@rec], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>R$ " & FORMAT([@tk], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right'><span style='display:inline-flex;align-items:center;gap:5px;background:rgba(52,211,153,0.12);color:#34D399;font-size:10.5px;padding:2px 8px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#34D399;display:inline-block'></span>Ativo</span></td></tr>",
					"",
					[@sk], ASC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;display:flex;flex-direction:column'><div style='font-size:16px;font-weight:600;color:#fff'>Todos os Clientes</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>" & FORMAT([Total Clientes], "#,0") & " clientes · ordenado por " & _ord & "</div><div style='flex:1;overflow-y:auto'><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Cliente</th>" & _th & "Cidade</th>" & _th & "Estado</th>" & _th & "Região</th>"
				& _thn & "Pedidos</th>" & _thn & "Receita</th>" & _thn & "Ticket</th>" & _thn & "Status</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000077

	measure 'Total Produtos' = COUNTROWS(dProduto)
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000080

	measure Categorias = COUNTROWS(dCategoria)
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000081

	measure 'HTML Card Total Produtos' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Total Produtos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z'/><polyline points='3.27 6.96 12 12.01 20.73 6.96'/><line x1='12' y1='22.08' x2='12' y2='12'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Total Produtos], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>no catálogo</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000082

	measure 'HTML Card Categorias' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Categorias</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polygon points='12 2 2 7 12 12 22 7 12 2'/><polyline points='2 17 12 22 22 17'/><polyline points='2 12 12 17 22 12'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Categorias], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>categorias ativas</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000083

	measure 'HTML Card Margem Media' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Margem Média</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='19' y1='5' x2='5' y2='19'/><circle cx='6.5' cy='6.5' r='2.5'/><circle cx='17.5' cy='17.5' r='2.5'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Margem %], "0.0%") & "</div><div style='font-size:11.5px;color:#34D399;margin-top:8px'>margem bruta geral</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000084

	measure 'HTML Card Qtd Vendida' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Qtd. Total Vendida</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='12' y1='20' x2='12' y2='10'/><line x1='18' y1='20' x2='18' y2='4'/><line x1='6' y1='20' x2='6' y2='16'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Total Quantidade], "#,0") & " un</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>unidades vendidas</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000085

	measure 'HTML Top Produtos' =
			VAR _base =
				ADDCOLUMNS(
					TOPN(8, SUMMARIZE(dProduto, dProduto[IDPRODUTO], dProduto[NOME], dCategoria[NOME], dProduto[CUSTO_MEDIO], dProduto[VALOR_UNITARIO]), [Total Receita], DESC),
					"@rec", [Total Receita], "@qtd", [Total Quantidade], "@marg", [Margem %]
				)
			VAR _rk = ADDCOLUMNS(_base, "@rk", RANKX(_base, [@rec], , DESC, DENSE))
			VAR _th = "<th style='text-align:left;padding:7px 9px;color:#6B6B85;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>"
			VAR _thn = "<th style='text-align:right;padding:7px 9px;color:#6B6B85;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>"
			VAR _rows =
				CONCATENATEX(
					_rk,
					VAR _m = [@marg]
					VAR _c = IF(_m >= 0.30, "#34D399", IF(_m >= 0.15, "#F59E0B", "#F87171"))
					VAR _b = IF(_m >= 0.30, "rgba(52,211,153,0.14)", IF(_m >= 0.15, "rgba(245,158,11,0.14)", "rgba(248,113,113,0.14)"))
					RETURN "<tr style='border-top:1px solid #16162A'><td style='padding:7px 9px;white-space:nowrap'><span style='display:inline-block;width:20px;height:20px;line-height:20px;text-align:center;border-radius:6px;background:rgba(139,92,246,0.15);color:#A78BFA;font-size:10.5px;font-weight:700;margin-right:8px'>" & [@rk] & "</span><span style='color:#E5E7EB;font-size:12px'>" & dProduto[NOME]
					& "</span></td><td style='padding:7px 9px;color:#9A9AB5;font-size:11.5px'>" & dCategoria[NOME]
					& "</td><td style='padding:7px 9px;text-align:right;color:#C8C8DC;font-size:11.5px'>R$ " & FORMAT(dProduto[CUSTO_MEDIO], "#,0")
					& "</td><td style='padding:7px 9px;text-align:right;color:#C8C8DC;font-size:11.5px'>R$ " & FORMAT(dProduto[VALOR_UNITARIO], "#,0")
					& "</td><td style='padding:7px 9px;text-align:right'><span style='border:1px solid " & _c & ";color:" & _c & ";background:" & _b & ";border-radius:20px;padding:2px 9px;font-size:11px;font-weight:600'>" & FORMAT(_m, "0.0%") & "</span></td><td style='padding:7px 9px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@qtd], "#,0")
					& "</td><td style='padding:7px 9px;text-align:right;color:#fff;font-size:12px;font-weight:600'>R$ " & FORMAT([@rec], "#,0") & "</td></tr>",
					"",
					[@rec], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px'><div style='font-size:15px;font-weight:600;color:#fff'>Catálogo de Produtos</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>Top 8 · maiores receitas</div><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Produto</th>" & _th & "Categoria</th>" & _thn & "Custo</th>" & _thn & "Valor</th>" & _thn & "Margem</th>" & _thn & "Qtd</th>" & _thn & "Receita</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000086

	measure 'HTML Catalogo Produtos' =
			VAR _ord = SELECTEDVALUE('Ordenar Produtos'[Opção], "Receita (maior)")
			VAR _base =
				ADDCOLUMNS(
					SUMMARIZE(dProduto, dProduto[IDPRODUTO], dProduto[NOME], dCategoria[NOME], dProduto[CUSTO_MEDIO], dProduto[VALOR_UNITARIO]),
					"@rec", [Total Receita], "@qtd", [Total Quantidade], "@marg", [Margem %]
				)
			VAR _sorted =
				ADDCOLUMNS(_base, "@sk",
					SWITCH(_ord,
						"Nome (A-Z)", RANKX(_base, dProduto[NOME], , ASC, DENSE),
						"Qtd (maior)", RANKX(_base, [@qtd], , DESC, DENSE),
						"Margem (maior)", RANKX(_base, [@marg], , DESC, DENSE),
						RANKX(_base, [@rec], , DESC, DENSE)
					))
			VAR _th = "<th style='position:sticky;top:0;background:#14142A;text-align:left;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _thn = "<th style='position:sticky;top:0;background:#14142A;text-align:right;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _rows =
				CONCATENATEX(
					_sorted,
					VAR _m = [@marg]
					VAR _c = IF(_m >= 0.30, "#34D399", IF(_m >= 0.15, "#F59E0B", "#F87171"))
					VAR _b = IF(_m >= 0.30, "rgba(52,211,153,0.14)", IF(_m >= 0.15, "rgba(245,158,11,0.14)", "rgba(248,113,113,0.14)"))
					RETURN "<tr style='border-top:1px solid #16162A'><td style='padding:7px 10px;color:#E5E7EB;font-size:12px'>" & dProduto[NOME]
					& "</td><td style='padding:7px 10px;color:#9A9AB5;font-size:11.5px'>" & dCategoria[NOME]
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>R$ " & FORMAT(dProduto[CUSTO_MEDIO], "#,0.00")
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>R$ " & FORMAT(dProduto[VALOR_UNITARIO], "#,0.00")
					& "</td><td style='padding:7px 10px;text-align:right'><span style='border:1px solid " & _c & ";color:" & _c & ";background:" & _b & ";border-radius:20px;padding:2px 9px;font-size:11px;font-weight:600'>" & FORMAT(_m, "0.0%") & "</span></td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@qtd], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right;color:#fff;font-size:12px;font-weight:600'>R$ " & FORMAT([@rec], "#,0") & "</td></tr>",
					"",
					[@sk], ASC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;display:flex;flex-direction:column'><div style='font-size:16px;font-weight:600;color:#fff'>Todos os Produtos</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>" & FORMAT([Total Produtos], "#,0") & " produtos · ordenado por " & _ord & "</div><div style='flex:1;overflow-y:auto'><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Produto</th>" & _th & "Categoria</th>" & _thn & "Custo Médio</th>" & _thn & "Valor Unit.</th>" & _thn & "Margem</th>" & _thn & "Qtd. Vendida</th>" & _thn & "Receita</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000086B

	measure 'Total Fornecedores' = COUNTROWS(dFornecedor)
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000090

	measure 'Fornecedores Ativos' = CALCULATE(COUNTROWS(dFornecedor), FILTER(dFornecedor, ISBLANK(dFornecedor[FIM])))
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000091

	measure 'Fornecedores Inativos' = CALCULATE(COUNTROWS(dFornecedor), FILTER(dFornecedor, NOT ISBLANK(dFornecedor[FIM])))
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000092

	measure 'Produtos Fornecidos' = DISTINCTCOUNT(fVendas[IDPRODUTO])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000093

	measure 'HTML Card Total Fornecedores' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Total Fornecedores</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='1' y='3' width='15' height='13'/><polygon points='16 8 20 8 23 11 23 16 16 16 16 8'/><circle cx='5.5' cy='18.5' r='2.5'/><circle cx='18.5' cy='18.5' r='2.5'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Total Fornecedores], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>cadastrados</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000094

	measure 'HTML Card Fornecedores Ativos' =
			VAR _pct = FORMAT(DIVIDE([Fornecedores Ativos], [Total Fornecedores]), "0%")
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Ativos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M22 11.08V12a10 10 0 1 1-5.93-9.14'/><polyline points='22 4 12 14.01 9 11.01'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Fornecedores Ativos], "#,0") & "</div><div style='font-size:11.5px;color:#34D399;margin-top:8px'>" & _pct & " ativos</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000095

	measure 'HTML Card Fornecedores Inativos' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Inativos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><line x1='15' y1='9' x2='9' y2='15'/><line x1='9' y1='9' x2='15' y2='15'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Fornecedores Inativos], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>contratos encerrados</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000096

	measure 'HTML Card Produtos Fornecidos' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Produtos Fornecidos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z'/><polyline points='3.27 6.96 12 12.01 20.73 6.96'/><line x1='12' y1='22.08' x2='12' y2='12'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Produtos Fornecidos], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>itens distintos</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000097

	measure 'HTML Cadastro Fornecedores' =
			VAR _base =
				ADDCOLUMNS(
					SUMMARIZE(dFornecedor, dFornecedor[IDFORNECEDOR], dFornecedor[NOME], dFornecedor[INICIO], dFornecedor[FIM]),
					"@prod", CALCULATE(DISTINCTCOUNT(fVendas[IDPRODUTO])), "@custo", [Total Custo]
				)
			VAR _th = "<th style='position:sticky;top:0;background:#14142A;text-align:left;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _thn = "<th style='position:sticky;top:0;background:#14142A;text-align:right;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _rows =
				CONCATENATEX(
					_base,
					VAR _fim = dFornecedor[FIM]
					VAR _ativo = ISBLANK(_fim)
					VAR _fimTxt = IF(_ativo, "—", FORMAT(_fim, "dd/mm/yyyy"))
					VAR _badge = IF(_ativo, "<span style='display:inline-flex;align-items:center;gap:5px;background:rgba(52,211,153,0.12);color:#34D399;font-size:10.5px;padding:2px 8px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#34D399;display:inline-block'></span>Ativo</span>", "<span style='display:inline-flex;align-items:center;gap:5px;background:rgba(120,120,140,0.15);color:#9A9AB5;font-size:10.5px;padding:2px 8px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#9A9AB5;display:inline-block'></span>Inativo</span>")
					RETURN "<tr style='border-top:1px solid #16162A'><td style='padding:7px 10px;color:#E5E7EB;font-size:12px'>" & dFornecedor[NOME]
					& "</td><td style='padding:7px 10px;color:#9A9AB5;font-size:11.5px'>" & FORMAT(dFornecedor[INICIO], "dd/mm/yyyy")
					& "</td><td style='padding:7px 10px;color:#9A9AB5;font-size:11.5px'>" & _fimTxt
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@prod], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right;color:#fff;font-size:12px;font-weight:600'>R$ " & FORMAT([@custo], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right'>" & _badge & "</td></tr>",
					"",
					[@custo], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;display:flex;flex-direction:column'><div style='font-size:15px;font-weight:600;color:#fff'>Cadastro de Fornecedores</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>" & FORMAT([Total Fornecedores], "#,0") & " fornecedores · ordenados por custo fornecido</div><div style='flex:1;overflow-y:auto'><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Fornecedor</th>" & _th & "Início Contrato</th>" & _th & "Fim Contrato</th>" & _thn & "Produtos</th>" & _thn & "Custo Fornecido</th>" & _thn & "Status</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000098

	measure 'HTML Regioes Tiles' =
			VAR _tot = CALCULATE([Total Receita], ALL(dCliente[REGIAO]))
			VAR _base = ADDCOLUMNS(VALUES(dCliente[REGIAO]), "@rec", [Total Receita], "@cli", DISTINCTCOUNT(dCliente[IDCLIENTE]))
			VAR _max = MAXX(_base, [@rec])
			VAR _cards =
				CONCATENATEX(
					_base,
					VAR _op = FORMAT(0.12 + DIVIDE([@rec], _max) * 0.5, "0.00")
					VAR _pct = FORMAT(DIVIDE([@rec], _tot), "0.0%")
					RETURN "<div style='background:rgba(139,92,246," & _op & ");border:1px solid rgba(139,92,246,0.18);border-radius:10px;padding:12px 14px;margin-bottom:8px;display:flex;align-items:center;justify-content:space-between'><div><div style='font-size:12px;font-weight:600;color:#E2E2F0;text-transform:uppercase;letter-spacing:.03em'>" & dCliente[REGIAO] & "</div><div style='font-size:10.5px;color:#C3B4EE;margin-top:3px'>" & FORMAT([@cli], "#,0") & " clientes · " & _pct & "</div></div><div style='font-size:16px;font-weight:700;color:#fff'>R$ " & FORMAT(DIVIDE([@rec],1000000), "#,0.0") & " mi</div></div>",
					"",
					[@rec], DESC
				)
			RETURN "<div style='font-family:sans-serif;height:100%;box-sizing:border-box;display:flex;flex-direction:column'>" & _cards & "</div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000A0

	measure 'HTML Estados Tabela' =
			VAR _base =
				ADDCOLUMNS(
					SUMMARIZE(dCliente, dCliente[ESTADO], dCliente[REGIAO]),
					"@cli", DISTINCTCOUNT(dCliente[IDCLIENTE]), "@ped", [Nº de Pedidos], "@rec", [Total Receita]
				)
			VAR _th = "<th style='position:sticky;top:0;background:#14142A;text-align:left;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _thn = "<th style='position:sticky;top:0;background:#14142A;text-align:right;padding:8px 10px;color:#8A8AA8;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:.04em;z-index:1'>"
			VAR _rows =
				CONCATENATEX(
					_base,
					VAR _cap = SWITCH(dCliente[ESTADO], "AC","Rio Branco", "AL","Maceió", "AP","Macapá", "AM","Manaus", "BA","Salvador", "CE","Fortaleza", "DF","Brasília", "ES","Vitória", "GO","Goiânia", "MA","São Luís", "MT","Cuiabá", "MS","Campo Grande", "MG","Belo Horizonte", "PA","Belém", "PB","João Pessoa", "PR","Curitiba", "PE","Recife", "PI","Teresina", "RJ","Rio de Janeiro", "RN","Natal", "RS","Porto Alegre", "RO","Porto Velho", "RR","Boa Vista", "SC","Florianópolis", "SP","São Paulo", "SE","Aracaju", "TO","Palmas", "—")
					RETURN "<tr style='border-top:1px solid #16162A'><td style='padding:7px 10px;color:#E5E7EB;font-size:12px;font-weight:600'>" & dCliente[ESTADO]
					& "</td><td style='padding:7px 10px;color:#9A9AB5;font-size:11.5px'>" & _cap
					& "</td><td style='padding:7px 10px;color:#7A7A98;font-size:11.5px'>" & dCliente[REGIAO]
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@cli], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right;color:#C8C8DC;font-size:11.5px'>" & FORMAT([@ped], "#,0")
					& "</td><td style='padding:7px 10px;text-align:right;color:#fff;font-size:12px;font-weight:600'>R$ " & FORMAT([@rec], "#,0") & "</td></tr>",
					"",
					[@rec], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;display:flex;flex-direction:column'><div style='font-size:15px;font-weight:600;color:#fff'>Todos os Estados</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>" & FORMAT([Qtd Estados], "#,0") & " estados · ordenado por receita</div><div style='flex:1;overflow-y:auto'><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Estado</th>" & _th & "Capital</th>" & _th & "Região</th>" & _thn & "Clientes</th>" & _thn & "Pedidos</th>" & _thn & "Receita</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000A1

	measure 'HTML Card Total Notas' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Total de Notas</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z'/><polyline points='14 2 14 8 20 8'/><line x1='16' y1='13' x2='8' y2='13'/><line x1='16' y1='17' x2='8' y2='17'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & FORMAT([Nº de Pedidos], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>notas fiscais emitidas</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000B0

	measure 'HTML Card Receita Vendas' =
			VAR _var = [Receita Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), "receita total", (IF(_up, "+", "") & FORMAT(_var, "0.0%") & " vs mês ant."))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Receita Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='12' y1='2' x2='12' y2='22'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg></div></div><div style='font-size:25px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>R$ " & FORMAT([Total Receita], "#,0") & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & "</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000B1

	measure 'HTML Card Lucro Vendas' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Lucro Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='22 7 13.5 15.5 8.5 10.5 2 17'/><polyline points='16 7 22 7 22 13'/></svg></div></div><div style='font-size:25px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>R$ " & FORMAT([Lucro Bruto], "#,0") & "</div><div style='font-size:11.5px;color:#34D399;margin-top:8px'>" & FORMAT([Margem %], "0.0%") & " de margem</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000B2

	measure 'HTML Card Custo Vendas' = "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Custo Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='22 17 13.5 8.5 8.5 13.5 2 7'/><polyline points='16 17 22 17 22 11'/></svg></div></div><div style='font-size:25px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>R$ " & FORMAT([Total Custo], "#,0") & "</div><div style='font-size:11.5px;color:#6B6B85;margin-top:8px'>custo das mercadorias</div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000B3

	measure 'HTML Vendas Recentes' =
			VAR _top = TOPN(30, fVendas, fVendas[IDTEMPO], DESC)
			VAR _th = "<th style='position:sticky;top:0;background:#14142A;text-align:left;padding:7px 9px;color:#8A8AA8;font-size:9.5px;font-weight:600;text-transform:uppercase;letter-spacing:.03em;z-index:1'>"
			VAR _thn = "<th style='position:sticky;top:0;background:#14142A;text-align:right;padding:7px 9px;color:#8A8AA8;font-size:9.5px;font-weight:600;text-transform:uppercase;letter-spacing:.03em;z-index:1'>"
			VAR _rows =
				CONCATENATEX(
					_top,
					"<tr style='border-top:1px solid #16162A'><td style='padding:6px 9px;color:#C8C8DC;font-size:11px;font-weight:600'>" & fVendas[IDNOTA]
					& "</td><td style='padding:6px 9px;color:#9A9AB5;font-size:11px'>" & FORMAT(fVendas[IDTEMPO], "dd/mm/yy")
					& "</td><td style='padding:6px 9px;color:#E5E7EB;font-size:11px'>" & RELATED(dCliente[NOME])
					& "</td><td style='padding:6px 9px;color:#9A9AB5;font-size:11px'>" & RELATED(dVendedor[NOME])
					& "</td><td style='padding:6px 9px;color:#9A9AB5;font-size:11px'>" & RELATED(dCategoria[NOME])
					& "</td><td style='padding:6px 9px;color:#9A9AB5;font-size:11px'>" & RELATED(dForma[FORMA])
					& "</td><td style='padding:6px 9px;text-align:right;color:#C8C8DC;font-size:11px'>" & FORMAT(fVendas[QUANTIDADE], "#,0")
					& "</td><td style='padding:6px 9px;text-align:right;color:#fff;font-size:11px;font-weight:600'>R$ " & FORMAT(fVendas[TOTAL_ITEM], "#,0")
					& "</td><td style='padding:6px 9px;text-align:right;color:#34D399;font-size:11px'>R$ " & FORMAT(fVendas[LUCRO_TOTAL], "#,0")
					& "</td><td style='padding:6px 9px;text-align:right'><span style='display:inline-flex;align-items:center;gap:4px;background:rgba(52,211,153,0.12);color:#34D399;font-size:10px;padding:2px 7px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#34D399;display:inline-block'></span>Concluída</span></td></tr>",
					"",
					fVendas[IDTEMPO], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;display:flex;flex-direction:column'><div style='font-size:15px;font-weight:600;color:#fff'>Vendas Recentes</div><div style='font-size:11px;color:#8888A8;margin-top:2px;margin-bottom:10px'>Últimas 30 transações</div><div style='flex:1;overflow-y:auto'><table style='width:100%;border-collapse:collapse'><thead><tr>"
				& _th & "Nota</th>" & _th & "Data</th>" & _th & "Cliente</th>" & _th & "Vendedor</th>" & _th & "Categoria</th>" & _th & "Pagamento</th>" & _thn & "Qtd</th>" & _thn & "Total</th>" & _thn & "Lucro</th>" & _thn & "Status</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-0000000000B4

	column Coluna
		lineageTag: 076459bf-7533-4efa-b92e-4a74f3e4e4e0
		summarizeBy: none
		isNameInferred
		sourceColumn: [Coluna]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = DATATABLE("Coluna", STRING, {{""}})

	annotation PBI_Id = 4f2cd5e765c349be8e713f7427d53d36

