table _Medidas
	lineageTag: 7a641823-7cda-46dc-ab66-b6ea2ffc0744

	measure 'Lucro Bruto' = SUM(fVendas[LUCRO_TOTAL])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1b2b9e1c-5089-4e9f-b119-83e445472653

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Margem %' = DIVIDE([Lucro Bruto], [Total Receita], 0)
		lineageTag: e4aeb396-44b2-443b-b138-b0b72cd3b86c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rank Vendedor' =
			
			RANKX(
			    ALL(dVendedor[NOME]),
			    [Total Receita],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: a9f790b2-6c03-4da0-bfef-ae192a918a83

	measure 'Receita Eletronicos' =
			
			CALCULATE(
			    [Total Receita],
			    dCategoria[NOME] IN {"CELULARES","INFORMATICA","TV E AUDIO"}
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 5946beba-49ed-4000-a947-d6d39061c901

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Custo' = SUM(fVendas[CUSTO_TOTAL])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 100f2cb6-21b1-41b8-9f64-2592760509f7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Receita' = SUM(fVendas[TOTAL_ITEM])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: facc93dd-f2fb-4930-997f-94697f87d656

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'HTML Abertura' = "<div style=""position:absolute;inset:0;width:100%;height:100%;min-height:680px;background:#09091A;background-image:radial-gradient(ellipse 70% 50% at 50% 0%, rgba(139,92,246,0.10) 0%, transparent 70%);display:flex;align-items:center;justify-content:center;font-family:'Segoe UI',sans-serif""><style>@keyframes iavpulse{0%,100%{opacity:.35;transform:scaleX(.82)}50%{opacity:1;transform:scaleX(1)}}@keyframes iavslide{0%{left:-40%}100%{left:100%}}.iavbar{height:6px;border-radius:9999px;background:#8B5CF6;transform-origin:left center;animation:iavpulse 1.4s ease-in-out infinite}.iavtrack{position:relative;width:240px;height:3px;border-radius:9999px;background:rgba(255,255,255,0.08);overflow:hidden;margin:0 auto}.iavtrack:after{content:'';position:absolute;top:0;left:0;height:100%;width:40%;border-radius:9999px;background:linear-gradient(90deg,#7C3AED,#8B5CF6,#A78BFA);animation:iavslide 1.5s cubic-bezier(.65,0,.35,1) infinite}</style><div style=""text-align:center""><div style=""display:flex;align-items:center;gap:18px;justify-content:center;margin-bottom:30px""><div style=""display:flex;flex-direction:column;gap:7px;align-items:flex-start""><span class=""iavbar"" style=""width:58px""></span><span class=""iavbar"" style=""width:38px;animation-delay:.18s""></span><span class=""iavbar"" style=""width:20px;animation-delay:.36s""></span></div><div style=""text-align:left""><div style=""font-size:40px;font-weight:700;letter-spacing:-0.03em;line-height:1;color:#fff"">IA Vendas</div><div style=""font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#70709A;margin-top:8px"">Grupo 4 &middot; Biopark Edu</div></div></div><div class=""iavtrack""></div><div style=""font-size:13px;letter-spacing:0.04em;color:#B0B0CC;margin-top:22px"">Carregando an&aacute;lise de vendas&hellip;</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000002

	column Coluna
		lineageTag: 076459bf-7533-4efa-b92e-4a74f3e4e4e0
		summarizeBy: none
		isNameInferred
		sourceColumn: [Coluna]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = DATATABLE("Coluna", STRING, {{""}})

	annotation PBI_Id = 4f2cd5e765c349be8e713f7427d53d36

