table _Medidas
	lineageTag: 7a641823-7cda-46dc-ab66-b6ea2ffc0744

	measure 'Lucro Bruto' = SUM(fVendas[LUCRO_TOTAL])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1b2b9e1c-5089-4e9f-b119-83e445472653

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Margem %' = DIVIDE([Lucro Bruto], [Total Receita], 0)
		lineageTag: e4aeb396-44b2-443b-b138-b0b72cd3b86c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rank Vendedor' =
			
			RANKX(
			    ALL(dVendedor[NOME]),
			    [Total Receita],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: a9f790b2-6c03-4da0-bfef-ae192a918a83

	measure 'Receita Eletronicos' =
			
			CALCULATE(
			    [Total Receita],
			    dCategoria[NOME] IN {"CELULARES","INFORMATICA","TV E AUDIO"}
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 5946beba-49ed-4000-a947-d6d39061c901

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Custo' = SUM(fVendas[CUSTO_TOTAL])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 100f2cb6-21b1-41b8-9f64-2592760509f7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Receita' = SUM(fVendas[TOTAL_ITEM])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: facc93dd-f2fb-4930-997f-94697f87d656

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'HTML Abertura' = "<div style=""position:absolute;inset:0;width:100%;height:100%;min-height:680px;background:#09091A;background-image:radial-gradient(ellipse 70% 50% at 50% 0%, rgba(139,92,246,0.10) 0%, transparent 70%);display:flex;align-items:center;justify-content:center;font-family:'Segoe UI',sans-serif""><style>@keyframes iavpulse{0%,100%{opacity:.35;transform:scaleX(.82)}50%{opacity:1;transform:scaleX(1)}}@keyframes iavslide{0%{left:-40%}100%{left:100%}}.iavbar{height:6px;border-radius:9999px;background:#8B5CF6;transform-origin:left center;animation:iavpulse 1.4s ease-in-out infinite}.iavtrack{position:relative;width:240px;height:3px;border-radius:9999px;background:rgba(255,255,255,0.08);overflow:hidden;margin:0 auto}.iavtrack:after{content:'';position:absolute;top:0;left:0;height:100%;width:40%;border-radius:9999px;background:linear-gradient(90deg,#7C3AED,#8B5CF6,#A78BFA);animation:iavslide 1.5s cubic-bezier(.65,0,.35,1) infinite}</style><div style=""text-align:center""><div style=""display:flex;align-items:center;gap:18px;justify-content:center;margin-bottom:30px""><div style=""display:flex;flex-direction:column;gap:7px;align-items:flex-start""><span class=""iavbar"" style=""width:58px""></span><span class=""iavbar"" style=""width:38px;animation-delay:.18s""></span><span class=""iavbar"" style=""width:20px;animation-delay:.36s""></span></div><div style=""text-align:left""><div style=""font-size:40px;font-weight:700;letter-spacing:-0.03em;line-height:1;color:#fff"">IA Vendas</div><div style=""font-size:11px;letter-spacing:0.16em;text-transform:uppercase;color:#70709A;margin-top:8px"">Grupo 4 &middot; Biopark Edu</div></div></div><div class=""iavtrack""></div><div style=""font-size:13px;letter-spacing:0.04em;color:#B0B0CC;margin-top:22px"">Carregando an&aacute;lise de vendas&hellip;</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000002

	measure 'Clientes Únicos' = DISTINCTCOUNT(dCliente[IDCLIENTE])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000010

	measure 'Total Quantidade' = SUM(fVendas[QUANTIDADE])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000011

	measure 'Qtd Fornecedores' = DISTINCTCOUNT(dFornecedor[IDFORNECEDOR])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000012

	measure 'Qtd Estados' = DISTINCTCOUNT(dCliente[ESTADO])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000013

	measure 'Fornecedores Vendendo' = DISTINCTCOUNT(fVendas[IDFORNECEDOR])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000014

	measure 'HTML Logo' = "<div style=""display:flex;align-items:center;gap:11px;height:100%;padding-left:6px;font-family:'Segoe UI',sans-serif""><div style=""display:flex;flex-direction:column;gap:4px""><span style=""display:block;height:4px;width:30px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:19px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:9px;border-radius:9px;background:#8B5CF6""></span></div><div><div style=""font-size:18px;font-weight:700;color:#fff;line-height:1"">IA Vendas</div><div style=""font-size:8px;letter-spacing:0.14em;text-transform:uppercase;color:#70709A;margin-top:3px"">Grupo 4</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000015

	measure 'Nº de Pedidos' = DISTINCTCOUNT(fVendas[IDNOTA])
		formatString: #,0
		lineageTag: a1a1a1a1-0000-4000-8000-000000000020

	measure 'Ticket Médio' = DIVIDE([Total Receita], [Nº de Pedidos])
		formatString: "R$"\ #,0.00
		lineageTag: a1a1a1a1-0000-4000-8000-000000000021

	measure 'HTML Sidebar' = "<div style=""height:100%;box-sizing:border-box;background:#0B0B1A;border-right:1px solid #1C1C30;padding-top:16px;font-family:'Segoe UI',sans-serif""><div style=""display:flex;align-items:center;gap:10px;height:80px;padding-left:18px""><div style=""display:flex;flex-direction:column;gap:4px""><span style=""display:block;height:4px;width:28px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:18px;border-radius:9px;background:#8B5CF6""></span><span style=""display:block;height:4px;width:9px;border-radius:9px;background:#8B5CF6""></span></div><div><div style=""font-size:17px;font-weight:700;color:#fff;line-height:1"">IA Vendas</div><div style=""font-size:8px;letter-spacing:0.14em;text-transform:uppercase;color:#70709A;margin-top:3px"">Grupo 4</div></div></div><div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Visão Geral</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Clientes</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Produtos</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Fornecedores</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Regiões</div><div style=""height:40px;line-height:40px;padding-left:20px;color:#B0B0CC;font-size:12.5px;white-space:nowrap""><span style=""display:inline-block;width:6px;height:6px;border-radius:50%;background:#8B5CF6;margin-right:11px;vertical-align:middle""></span>Vendas</div></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000030

	measure 'Receita Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Total Receita]
			VAR _ant = CALCULATE([Total Receita], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000040

	measure 'Lucro Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Lucro Bruto]
			VAR _ant = CALCULATE([Lucro Bruto], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000041

	measure 'Pedidos Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Nº de Pedidos]
			VAR _ant = CALCULATE([Nº de Pedidos], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000042

	measure 'Ticket Var %' =
			VAR _nYM = COUNTROWS(SUMMARIZE(dTempo, dTempo[ANO], dTempo[MES]))
			VAR _atual = [Ticket Médio]
			VAR _ant = CALCULATE([Ticket Médio], DATEADD(dTempo[DATA], -1, MONTH))
			RETURN IF(_nYM <> 1 || ISBLANK(_atual) || ISBLANK(_ant) || _ant = 0, BLANK(), DIVIDE(_atual - _ant, _ant))
		lineageTag: a1a1a1a1-0000-4000-8000-000000000043

	measure 'HTML Card Receita' =
			VAR _v = "R$ " & FORMAT([Total Receita], "#,0")
			VAR _var = [Receita Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Receita Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='12' y1='2' x2='12' y2='22'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000050

	measure 'HTML Card Lucro' =
			VAR _v = "R$ " & FORMAT([Lucro Bruto], "#,0")
			VAR _var = [Lucro Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Lucro Total</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='22 7 13.5 15.5 8.5 10.5 2 17'/><polyline points='16 7 22 7 22 13'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000051

	measure 'HTML Card Ticket' =
			VAR _v = "R$ " & FORMAT([Ticket Médio], "#,0.00")
			VAR _var = [Ticket Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Ticket Médio</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z'/><path d='M16 8h-6'/><path d='M16 12h-6'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000052

	measure 'HTML Card Pedidos' =
			VAR _v = FORMAT([Nº de Pedidos], "#,0")
			VAR _var = [Pedidos Var %]
			VAR _up = COALESCE(_var, 0) >= 0
			VAR _cor = IF(ISBLANK(_var), "#6B6B85", IF(_up, "#34D399", "#F87171"))
			VAR _seta = IF(ISBLANK(_var), "", IF(_up, UNICHAR(9650) & " ", UNICHAR(9660) & " "))
			VAR _pct = IF(ISBLANK(_var), UNICHAR(8212), IF(_up, "+", "") & FORMAT(_var, "0.0%"))
			RETURN "<div style='height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px;font-family:sans-serif;display:flex;flex-direction:column;justify-content:space-between'><div style='display:flex;align-items:flex-start;justify-content:space-between'><div style='font-size:12px;color:#8888A8'>Nº de Pedidos</div><div style='width:34px;height:34px;border-radius:9px;background:rgba(139,92,246,0.12);display:flex;align-items:center;justify-content:center'><svg width='17' height='17' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='8' cy='21' r='1'/><circle cx='19' cy='21' r='1'/><path d='M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12'/></svg></div></div><div style='font-size:26px;font-weight:700;color:#fff;line-height:1;margin-top:6px'>" & _v & "</div><div style='font-size:11.5px;color:" & _cor & ";margin-top:8px'>" & _seta & _pct & " <span style='color:#6B6B85'>vs mês anterior</span></div></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000053

	measure 'HTML Top Clientes' =
			VAR _base =
				ADDCOLUMNS(
					TOPN(6, SUMMARIZE(dCliente, dCliente[NOME], dCliente[REGIAO]), [Total Receita], DESC),
					"@rec", [Total Receita],
					"@ped", [Nº de Pedidos]
				)
			VAR _rk = ADDCOLUMNS(_base, "@rk", RANKX(_base, [@rec], , DESC, DENSE))
			VAR _rows =
				CONCATENATEX(
					_rk,
					"<tr style='border-top:1px solid #16162A'><td style='padding:9px 8px;white-space:nowrap'><span style='display:inline-block;width:20px;height:20px;line-height:20px;text-align:center;border-radius:6px;background:rgba(139,92,246,0.15);color:#A78BFA;font-size:11px;font-weight:700;margin-right:9px'>"
					& [@rk] & "</span><span style='color:#E5E7EB;font-size:12.5px'>" & dCliente[NOME]
					& "</span></td><td style='padding:9px 8px;color:#7A7A98;font-size:12px'>" & dCliente[REGIAO]
					& "</td><td style='padding:9px 8px;text-align:right;color:#C8C8DC;font-size:12px'>" & FORMAT([@ped], "#,0")
					& "</td><td style='padding:9px 8px;text-align:right;color:#fff;font-size:12.5px;font-weight:600'>R$ " & FORMAT([@rec], "#,0")
					& "</td><td style='padding:9px 8px;text-align:right'><span style='display:inline-flex;align-items:center;gap:5px;background:rgba(52,211,153,0.12);color:#34D399;font-size:11px;padding:2px 8px;border-radius:20px'><span style='width:5px;height:5px;border-radius:50%;background:#34D399;display:inline-block'></span>Ativo</span></td></tr>",
					"",
					[@rec], DESC
				)
			RETURN
				"<div style='font-family:sans-serif;height:100%;box-sizing:border-box;background:#0E0E20;border:1px solid #1C1C30;border-radius:14px;padding:16px 18px'><div style='display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px'><div><div style='font-size:15px;font-weight:600;color:#fff'>Top Clientes</div><div style='font-size:11px;color:#8888A8;margin-top:2px'>Maiores receitas</div></div></div><table style='width:100%;border-collapse:collapse'><thead><tr><th style='text-align:left;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Cliente</th><th style='text-align:left;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Região</th><th style='text-align:right;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Pedidos</th><th style='text-align:right;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Receita</th><th style='text-align:right;padding:6px 8px;color:#6B6B85;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:.04em'>Status</th></tr></thead><tbody>"
				& _rows & "</tbody></table></div>"
		lineageTag: a1a1a1a1-0000-4000-8000-000000000060

	column Coluna
		lineageTag: 076459bf-7533-4efa-b92e-4a74f3e4e4e0
		summarizeBy: none
		isNameInferred
		sourceColumn: [Coluna]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = DATATABLE("Coluna", STRING, {{""}})

	annotation PBI_Id = 4f2cd5e765c349be8e713f7427d53d36

