table dCategoria
	lineageTag: e23be9d6-bc5e-41e5-8f1e-dba741ffb330

	column IDCATEGORIA
		dataType: int64
		formatString: 0
		lineageTag: cb65c004-ba20-4803-a8e4-8c72c068797c
		summarizeBy: none
		sourceColumn: IDCATEGORIA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: a4b7efb6-e6c1-4d9c-95bc-f28fe7136466
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	partition dCategoria = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Usuario\Documents\fuck_it\wesley\projeto_final_la\projeto-ia-vendas\data\dCategoria.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"IDCATEGORIA", Int64.Type}, {"NOME", type text}})
				in
				    #"Tipo Alterado"

	changedProperty = Name

	annotation PBI_ResultType = Table

