table dFornecedor
	lineageTag: f21c4fa6-f2a6-4040-9621-5c5e5052ad1f

	column IDFORNECEDOR
		dataType: int64
		formatString: 0
		lineageTag: e04c0dcb-02e6-4043-a964-3a899a5ac56b
		summarizeBy: none
		sourceColumn: IDFORNECEDOR

		annotation SummarizationSetBy = Automatic

	column INICIO
		dataType: dateTime
		formatString: General Date
		lineageTag: 406c5a79-033f-4c93-8ee6-a04ca172ecf0
		summarizeBy: none
		sourceColumn: INICIO

		annotation SummarizationSetBy = Automatic

	column FIM
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e371e12-3d5a-472d-9182-c281315e1f85
		summarizeBy: none
		sourceColumn: FIM

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: b9961cfc-cf23-485c-bc64-38452b70c40f
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	partition dFornecedor = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(BasePath & "dFornecedor.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"IDFORNECEDOR", Int64.Type}, {"INICIO", type datetime}, {"FIM", type datetime}, {"NOME", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"IDFORNECEDOR"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

