table dFornecedor
	lineageTag: f21c4fa6-f2a6-4040-9621-5c5e5052ad1f

	column IDFORNECEDOR
		dataType: int64
		formatString: 0
		lineageTag: e04c0dcb-02e6-4043-a964-3a899a5ac56b
		summarizeBy: sum
		sourceColumn: IDFORNECEDOR

		annotation SummarizationSetBy = Automatic

	column INICIO
		dataType: dateTime
		formatString: General Date
		lineageTag: 406c5a79-033f-4c93-8ee6-a04ca172ecf0
		summarizeBy: none
		sourceColumn: INICIO

		variation Variation
			isDefault
			relationship: ea93105f-4ad7-4da1-a155-11a0c8640523
			defaultHierarchy: LocalDateTable_226403b7-c610-4525-9cd2-5d8de706ac68.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column FIM
		dataType: dateTime
		formatString: General Date
		lineageTag: 2e371e12-3d5a-472d-9182-c281315e1f85
		summarizeBy: none
		sourceColumn: FIM

		variation Variation
			isDefault
			relationship: 756b2a54-2c53-4df9-8c23-95d3235a0f72
			defaultHierarchy: LocalDateTable_2a855a5b-b71c-4b7c-9c12-16519b896dd1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: b9961cfc-cf23-485c-bc64-38452b70c40f
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	partition dFornecedor = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Usuario\Documents\fuck_it\wesley\projeto_final_la\projeto-ia-vendas\data\dFornecedor.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"IDFORNECEDOR", Int64.Type}, {"INICIO", type datetime}, {"FIM", type datetime}, {"NOME", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"IDFORNECEDOR"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

