table dForma
	lineageTag: 6e65829f-6040-433e-bd10-a5164c4da6e0

	column IDFORMA
		dataType: int64
		formatString: 0
		lineageTag: 157699be-ff84-498f-a987-2b6ecf8b6713
		summarizeBy: none
		sourceColumn: IDFORMA

		annotation SummarizationSetBy = Automatic

	column FORMA
		dataType: string
		lineageTag: 8df3c979-d236-4b56-bbba-7850ab85a107
		summarizeBy: none
		sourceColumn: FORMA

		annotation SummarizationSetBy = Automatic

	partition dForma = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("..\..\..\..\data\dForma.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"IDFORMA", Int64.Type}, {"FORMA", type text}})
				in
				    #"Tipo Alterado"

	changedProperty = Name

	annotation PBI_ResultType = Table


