table dTempo
	lineageTag: 2d050c69-2dd8-4411-a1ed-2bd6547c5ab8

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f7d4e9d-a5a0-4099-9a8c-3f78826eef52
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: 5c2a1056-35a4-4078-97fc-1115312ff0da
			defaultHierarchy: LocalDateTable_ec7d9744-ada7-499f-8fa9-1d64029c3e41.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIA
		dataType: int64
		formatString: 0
		lineageTag: 59eea0b8-3570-4815-a85c-aeea56530f53
		summarizeBy: sum
		sourceColumn: DIA

		annotation SummarizationSetBy = Automatic

	column DIASEMANA
		dataType: string
		lineageTag: d9e1cb27-4fe0-4609-9a10-78c734d3246a
		summarizeBy: none
		sourceColumn: DIASEMANA

		annotation SummarizationSetBy = Automatic

	column MES
		dataType: int64
		formatString: 0
		lineageTag: 23916914-1dde-440f-a3e5-9492b71a3f8b
		summarizeBy: sum
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column NOMEMES
		dataType: string
		lineageTag: 5c60808c-0bd3-42bf-b0ca-5898fd64a08f
		summarizeBy: none
		sourceColumn: NOMEMES

		annotation SummarizationSetBy = Automatic

	column QUARTO
		dataType: int64
		formatString: 0
		lineageTag: f3b824bb-f828-4aa9-9408-321516c9866d
		summarizeBy: sum
		sourceColumn: QUARTO

		annotation SummarizationSetBy = Automatic

	column NOMEQUARTO
		dataType: string
		lineageTag: 5e5a89b8-683f-4875-ab10-3552b15dd1d2
		summarizeBy: none
		sourceColumn: NOMEQUARTO

		annotation SummarizationSetBy = Automatic

	column ANO
		dataType: int64
		formatString: 0
		lineageTag: ffbf6cea-d7ef-4fdd-b23b-52fd4f167327
		summarizeBy: sum
		sourceColumn: ANO

		annotation SummarizationSetBy = Automatic

	column ESTACAOANO
		dataType: string
		lineageTag: e7da47e2-2338-4b9c-abdc-fd73ce3aeda1
		summarizeBy: none
		sourceColumn: ESTACAOANO

		annotation SummarizationSetBy = Automatic

	column FIMSEMANA
		dataType: string
		lineageTag: 7fe77654-f64b-4471-8a79-7eea04f3ca53
		summarizeBy: none
		sourceColumn: FIMSEMANA

		annotation SummarizationSetBy = Automatic

	column DATACOMPLETA
		dataType: int64
		formatString: 0
		lineageTag: a66ee203-a8de-408e-bebc-c6ffb06c9ddd
		summarizeBy: sum
		sourceColumn: DATACOMPLETA

		annotation SummarizationSetBy = Automatic

	partition dTempo = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("..\..\..\..\data\dTempo.xlsx"), null, true),
				    Tabela2_Table = Fonte{[Item="Tabela2",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela2_Table,{{"DATA", type date}, {"DIA", Int64.Type}, {"DIASEMANA", type text}, {"MES", Int64.Type}, {"NOMEMES", type text}, {"QUARTO", Int64.Type}, {"NOMEQUARTO", type text}, {"ANO", Int64.Type}, {"ESTACAOANO", type text}, {"FIMSEMANA", type text}, {"DATACOMPLETA", Int64.Type}})
				in
				    #"Tipo Alterado"

	changedProperty = Name

	annotation PBI_ResultType = Table


