table dVendedor
	lineageTag: 47e1f4ab-287c-4a96-ab35-cafe64e4a35b

	column IDVENDEDOR
		dataType: int64
		formatString: 0
		lineageTag: 5fb1d6fc-b80c-448e-b98d-45afad59d817
		summarizeBy: none
		sourceColumn: IDVENDEDOR

		annotation SummarizationSetBy = Automatic

	column INICIO
		dataType: dateTime
		formatString: General Date
		lineageTag: 6e30bf18-0158-4e41-854c-2fad95142696
		summarizeBy: none
		sourceColumn: INICIO

		annotation SummarizationSetBy = Automatic

	column FIM
		dataType: dateTime
		formatString: General Date
		lineageTag: c46ad8a3-a214-4839-8573-3aabcea33228
		summarizeBy: none
		sourceColumn: FIM

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: aefb1a09-826d-4ed7-a6a6-6cab74dc274e
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: 9fd87a23-82e6-4c00-a1fb-c8325161589d
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column IDGERENTE
		dataType: int64
		formatString: 0
		lineageTag: 183a69a8-0346-46b8-a287-2e5d2bbb69ac
		summarizeBy: sum
		sourceColumn: IDGERENTE

		annotation SummarizationSetBy = Automatic

	partition dVendedor = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(BasePath & "dVendedor.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela1_Table,{{"IDVENDEDOR", Int64.Type}, {"INICIO", type datetime}, {"FIM", type datetime}, {"NOME", type text}, {"SEXO", type text}, {"IDGERENTE", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

