table fVendas
	lineageTag: 10f6e259-63b0-4a8c-819b-2bd8c77b262d

	column IDNOTA
		dataType: int64
		formatString: 0
		lineageTag: cc564df1-7b76-41b6-b975-db8be74ee5ff
		summarizeBy: none
		sourceColumn: IDNOTA

		annotation SummarizationSetBy = Automatic

	column IDCLIENTE
		dataType: int64
		formatString: 0
		lineageTag: 3180f897-c3e1-4493-b9ac-c79680fae8a9
		summarizeBy: none
		sourceColumn: IDCLIENTE

		annotation SummarizationSetBy = Automatic

	column IDVENDEDOR
		dataType: int64
		formatString: 0
		lineageTag: 7215b46a-14cc-4dcf-9747-a484d77313c8
		summarizeBy: none
		sourceColumn: IDVENDEDOR

		annotation SummarizationSetBy = Automatic

	column IDFORMA
		dataType: int64
		formatString: 0
		lineageTag: af83729f-1b45-4d4e-8a3d-78f38388c49e
		summarizeBy: none
		sourceColumn: IDFORMA

		annotation SummarizationSetBy = Automatic

	column IDPRODUTO
		dataType: int64
		formatString: 0
		lineageTag: 06a7fde8-7970-4d05-bdce-fd2e340f33fc
		summarizeBy: none
		sourceColumn: IDPRODUTO

		annotation SummarizationSetBy = Automatic

	column IDFORNECEDOR
		dataType: int64
		formatString: 0
		lineageTag: 324aaa32-f2d2-40b8-aac3-c2c1a033c7d8
		summarizeBy: none
		sourceColumn: IDFORNECEDOR

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE
		dataType: int64
		formatString: 0
		lineageTag: fedc5fa5-3643-4115-a357-f476ff8de0e2
		summarizeBy: sum
		sourceColumn: QUANTIDADE

		annotation SummarizationSetBy = Automatic

	column TOTAL_ITEM
		dataType: decimal
		formatString: 0
		lineageTag: ae912b8c-e98e-4c43-9400-32b5ebbf80f3
		summarizeBy: sum
		sourceColumn: TOTAL_ITEM

		annotation SummarizationSetBy = Automatic

	column CUSTO_TOTAL
		dataType: decimal
		formatString: 0
		lineageTag: 15d66bea-214e-4293-8411-1131e4cfe42b
		summarizeBy: sum
		sourceColumn: CUSTO_TOTAL

		annotation SummarizationSetBy = Automatic

	column LUCRO_TOTAL
		dataType: decimal
		formatString: 0
		lineageTag: 05f22c05-43a6-42e7-be41-d25776f0b4ba
		summarizeBy: sum
		sourceColumn: LUCRO_TOTAL

		annotation SummarizationSetBy = Automatic

	column IDTEMPO
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0794c87-a343-4e7e-b972-1131a25d0d77
		summarizeBy: none
		sourceColumn: IDTEMPO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fVendas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(BasePath & "fVendas.xlsx"), null, true),
				    Tabela1_Table = Fonte{[Item="Tabela1",Kind="Table"]}[Data],
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(Tabela1_Table, {{"TOTAL_ITEM", Currency.Type}}, "en-US"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"CUSTO_TOTAL", Currency.Type}}, "en-US"),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade1", {{"LUCRO_TOTAL", Currency.Type}}, "en-US"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade2",{{"IDNOTA", Int64.Type}, {"IDCLIENTE", Int64.Type}, {"IDVENDEDOR", Int64.Type}, {"IDFORMA", Int64.Type}, {"IDPRODUTO", Int64.Type}, {"IDFORNECEDOR", Int64.Type}, {"IDTEMPO", type text}, {"QUANTIDADE", Int64.Type}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado",{{"IDTEMPO", type date}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Tipo Alterado1",{{"IDTEMPO", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado2", "TEMPOID", each [IDTEMPO] - 32872),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"TEMPOID", type date}, {"IDTEMPO", type date}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado3",{"IDTEMPO"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"TEMPOID", "IDTEMPO"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas",{"IDNOTA", "IDCLIENTE", "IDVENDEDOR", "IDFORMA", "IDPRODUTO", "IDFORNECEDOR", "IDTEMPO", "QUANTIDADE", "TOTAL_ITEM", "CUSTO_TOTAL", "LUCRO_TOTAL"})
				in
				    #"Colunas Reordenadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

