table Tabela2
	lineageTag: 31f3a7bf-0588-4bc3-8661-d1be09ba1e4f

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: c35e3893-bb48-4e00-af17-a6c5450663ab
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIA
		dataType: int64
		formatString: 0
		lineageTag: 1dbab797-1aab-4ac6-974a-d7c39bff253e
		summarizeBy: sum
		sourceColumn: DIA

		annotation SummarizationSetBy = Automatic

	column DIASEMANA
		dataType: string
		lineageTag: 91f10c17-7eec-49c8-b31d-ce492cedf237
		summarizeBy: none
		sourceColumn: DIASEMANA

		annotation SummarizationSetBy = Automatic

	column MES
		dataType: int64
		formatString: 0
		lineageTag: 35a370d3-132e-4aeb-ae4a-425c376c04c2
		summarizeBy: sum
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column NOMEMES
		dataType: string
		lineageTag: a1efc248-a6be-4cf6-88d3-c00d51542d30
		summarizeBy: none
		sourceColumn: NOMEMES

		annotation SummarizationSetBy = Automatic

	column QUARTO
		dataType: int64
		formatString: 0
		lineageTag: 1b01ddaf-17d3-4742-9e21-a9062c398040
		summarizeBy: sum
		sourceColumn: QUARTO

		annotation SummarizationSetBy = Automatic

	column NOMEQUARTO
		dataType: string
		lineageTag: 1b01d9e9-b0ce-4c0b-ad82-42c2596ac03f
		summarizeBy: none
		sourceColumn: NOMEQUARTO

		annotation SummarizationSetBy = Automatic

	column ANO
		dataType: int64
		formatString: 0
		lineageTag: a5200c85-c8aa-445a-93d2-75e03a6456f6
		summarizeBy: sum
		sourceColumn: ANO

		annotation SummarizationSetBy = Automatic

	column ESTACAOANO
		dataType: string
		lineageTag: cf97257a-fa1f-45e2-9ff8-2a9f07971bf2
		summarizeBy: none
		sourceColumn: ESTACAOANO

		annotation SummarizationSetBy = Automatic

	column FIMSEMANA
		dataType: string
		lineageTag: 574044c5-8e35-44c0-8b3d-b3685bc3b2ea
		summarizeBy: none
		sourceColumn: FIMSEMANA

		annotation SummarizationSetBy = Automatic

	column DATACOMPLETA
		dataType: int64
		formatString: 0
		lineageTag: b7888fda-5a96-4ce7-8e7c-60e2016f62e5
		summarizeBy: sum
		sourceColumn: DATACOMPLETA

		annotation SummarizationSetBy = Automatic

	partition Tabela2 = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\daniel.furtado\Desktop\projeto-ia\projeto-ia-vendas\data\dTempo.xlsx"), null, true),
				    Tabela2_Table = Fonte{[Item="Tabela2",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela2_Table,{{"DATA", type date}, {"DIA", Int64.Type}, {"DIASEMANA", type text}, {"MES", Int64.Type}, {"NOMEMES", type text}, {"QUARTO", Int64.Type}, {"NOMEQUARTO", type text}, {"ANO", Int64.Type}, {"ESTACAOANO", type text}, {"FIMSEMANA", type text}, {"DATACOMPLETA", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

